name: portfolio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  font_awesome_flutter: ^10.6.0
  provider: ^6.1.5+1
  dotted_line: ^3.2.3
  sleek_circular_slider: ^2.1.0
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/human.png
    - assets/images/Me.jpeg
    - assets/images/me2.jpeg
